# docker-compose.yml #
# docker-compose rm -v to remove everything and build up
# WAS USED TO TEST IN A CONTAINER ENVIRONMET
version: "3.4"

# networks:
  # privatenetwork:

services:
  app:
    image: php:7.1.8-apache
    volumes:
      - "./:/app"
    working_dir: /app
    command: "php artisan serve --host=0.0.0.0 --port=8010"
    ports:
      - 8000:8000

volumes:
  block: {}
  # db-data: {}